ARG version
FROM almalinux:${version:-8}
ARG     Course="DockerforBeginners" \
        Trainer="Shiva Reddy" \
        Duration="10 hours"  \
        Topic="Dockerfiles" \
        Version="1.0" 
RUN echo "Trainer is ${Trainer},version is ${version}"
CMD ["sleep", "400"]    